site_name: EdgeFirst Studio Documentation
site_url: https://edgefirst.github.io/documentation/
site_description: EdgeFirst Studio Documentation
site_author: Au-Zone Technologies
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: indigo
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night        
        name: Dark mode
      primary: indigo
      accent: amber
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow

plugins:
  - awesome-nav
  - search

markdown_extensions:
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  consent:
    title: Privacy Settings
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2025 Au-Zone Technologies &mdash;
  <a href="#__consent">Privacy Settings</a>
