site_name: EdgeFirst Studio Documentation
site_url: https://doc.edgefirst.ai/
site_description: EdgeFirst Studio Documentation
site_author: Au-Zone Technologies
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: indigo
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: indigo
      accent: amber
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top    
    - toc.follow

validation:
  absolute_links: ignore
exclude_docs: |
  /discrete

plugins:
  - awesome-nav:
  - autorefs:
  - search:
  - include-markdown:
      rewrite_relative_urls: true
      heading_offset: 1
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_bases: false
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_toc: true
            heading_level: 3
            docstring_section_style: list
            show_docstring_description: true
            show_docstring_examples: true
          load_external_modules: true
          inventories:
          - https://docs.python.org/3/objects.inv
  - spellcheck:
      backends:
      - symspellpy 
      - codespell: 
          dictionaries: [clear, en-GB_to_en-US]
      known_words: assets/known_words.txt
      ignore_code: yes
      min_length: 2
      allow_unicode: no
      skip_files:
      - .nav.yml
      strict_only: yes

markdown_extensions:
  - admonition  
  - attr_list 
  - md_in_html   
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption
  - pymdownx.details  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true  
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    default: latest
    provider: mike
    alias: true
  analytics:
    provider: google
    property: G-N2QMRM1BZK
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Privacy Settings
    cookies:
      analytics:
        name: Google Analytics
        checked: true
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2025 Au-Zone Technologies &mdash;
  <a href="#__consent">Privacy Settings</a>
  