nav:
  - Home: index.md
  - Getting Started:
    - getting_started/index.md
    - getting_started/dataset.md
    - getting_started/models.md
    - getting_started/modules.md
  - enterprise
  - Datasets:
    - datasets/index.md
    - datasets/tutorials.md
    - datasets/zoo.md
    - datasets/format.md
  - models:
    - models/index.md
    - model:
      - training:
        - models/model/training/modelpack.md
        - models/model/training/fusion.md
      - validation:
        - models/model/validation/modelpack.md
        - models/model/validation/fusion.md
        - models/model/validation/metrics.md
    - models/augmentations.md
  - fusion
  - Middleware:
    - middleware/overview.md
    - middleware/topics.md
    - middleware/custom.md
    - API Reference:
      - middleware/api.md
      - middleware/api/edgefirst_msgs.md
      - middleware/api/foxglove_msgs.md
      - middleware/api/geometry_msgs.md
      - middleware/api/nav_msgs.md
      - middleware/api/sensor_msgs.md
      - middleware/api/std_msgs.md
      - middleware/api/builtin_interfaces.md
  - modules
