nav:
  - Home: index.md
  - Getting Started:
    - getting_started/index.md
    - getting_started/dataset.md
    - getting_started/models.md
    - getting_started/modules.md
  - enterprise
  - Datasets:
    - datasets/index.md
    - datasets/tutorials.md
    - datasets/zoo.md
    - datasets/format.md
  - Models:
    - models/index.md
    - models/augmentations.md
    - models/metrics.md
    - Modelpack:
      - models/modelpack/index.md
      - models/modelpack/training.md
      - models/modelpack/validation.md
    - Fusion:
      - models/fusion/index.md
      - models/fusion/training.md
      - models/fusion/validation.md
  - Middleware:
    - middleware/overview.md
    - middleware/topics.md
    - middleware/custom.md
    - API Reference:
      - middleware/api.md
      - middleware/api/edgefirst_msgs.md
      - middleware/api/foxglove_msgs.md
      - middleware/api/geometry_msgs.md
      - middleware/api/nav_msgs.md
      - middleware/api/sensor_msgs.md
      - middleware/api/std_msgs.md
      - middleware/api/builtin_interfaces.md
  - modules
