nav:
  #   - Home: https://edgefirst.studio
  - Getting Started:
      - index.md
      - getting_started/workflows.md
      - getting_started/studio.md
      - getting_started/datasets.md
      - getting_started/models.md
      - getting_started/perception.md
      - getting_started/platforms.md
  - Studio:
      - studio/index.md
      - studio/navigation.md
      - studio/access.md
      - studio/projects.md
      - Datasets:
          - studio/datasets/index.md
          - studio/datasets/gallery.md
          - studio/datasets/annotations.md
      - studio/agtg.md
      - studio/snapshots.md
      - studio/dataio.md
  - Datasets:
      - datasets/index.md
      - datasets/tutorials.md
      - datasets/format.md
      #   - datasets/types.md
      - datasets/zoo.md
  - Models:
      - models/index.md
      - Modelpack:
          - models/modelpack/index.md
          - models/modelpack/training.md
          - models/modelpack/validation.md
          - models/modelpack/deployment.md
      - Fusion:
          - models/fusion/index.md
          - models/fusion/training.md
          - models/fusion/validation.md
          - models/fusion/deployment.md
      - models/augmentations.md
      - models/metrics.md
  - Perception:
      - perception/index.md
      - Web UI:
          - perception/webui/walkthrough.md
          - perception/webui/configuration.md
      - Data Recording:
          - perception/mcap/recording.md
          - perception/mcap/replay.md
          - perception/mcap/publishing.md
          - perception/mcap/foxglove.md
          - perception/mcap/advanced_foxglove.md
      - perception/studio.md
      - Middleware Topics:
          - perception/topics.md
          - perception/topics/model.md
          - perception/topics/fusion.md
          - perception/topics/camera.md
          - perception/topics/radar.md
          - perception/topics/lidar.md
          - perception/topics/imu.md
          - perception/topics/navsat.md
      - perception/custom.md
      - Developer Guide:
          - perception/dev.md
          - perception/dev/python.md
      - API Reference:
          - perception/api.md
          - perception/api/edgefirst_msgs.md
          - perception/api/foxglove_msgs.md
          - perception/api/geometry_msgs.md
          - perception/api/nav_msgs.md
          - perception/api/sensor_msgs.md
          - perception/api/std_msgs.md
          - perception/api/builtin_interfaces.md
          - perception/api/studio.md
  - Platforms:
      - platforms/index.md
      - Maivin 1:
        - platforms/maivin/quickstart.md
        - platforms/maivin/walkthrough.md
        - platforms/maivin/configuration.md
        - platforms/maivin/networking.md
        - platforms/maivin/ssh.md
        - platforms/maivin/hardware.md
        - platforms/maivin/updates.md
        - platforms/maivin/release_notes.md        
      - Maivin 2:
        - platforms/maivin/quickstart.md
        - platforms/maivin/walkthrough.md
        - platforms/maivin/configuration.md
        - platforms/maivin/networking.md
        - platforms/maivin/ssh.md
        - platforms/maivin/hardware.md
        - platforms/maivin/updates.md
        - platforms/maivin/release_notes.md        
      - Raivin:
        - platforms/maivin/quickstart.md
        - platforms/maivin/walkthrough.md
        - platforms/maivin/configuration.md
        - platforms/maivin/networking.md
        - platforms/maivin/ssh.md
        - platforms/maivin/hardware.md
        - platforms/maivin/radar.md
        - platforms/maivin/updates.md
        - platforms/maivin/release_notes.md        
      - Raivin HD:
        - platforms/maivin/quickstart.md
        - platforms/maivin/walkthrough.md
        - platforms/maivin/configuration.md
        - platforms/maivin/networking.md
        - platforms/maivin/ssh.md
        - platforms/maivin/hardware.md
        - platforms/maivin/radar.md
        - platforms/maivin/updates.md
        - platforms/maivin/release_notes.md
      - NXP i.MX 8M Plus EVK:
        - platforms/imx8mp/quickstart.md
      - Nvidia Jetson:
        - platforms/jetson/quickstart.md
      - RaspberryPi:
        - platforms/raspberrypi/quickstart.md