nav:
  - Home: https://test.edgefirst.studio
  - Getting Started:
    - index.md
    - getting_started/login.md
    - getting_started/create_project.md
    - getting_started/capture_data.md
    - getting_started/annotate_dataset.md
    - getting_started/train_vision.md
    - getting_started/validate_vision.md
    - getting_started/deploy_model.md
    - User Workflows:
      - getting_started/workflows/index.md
      - getting_started/workflows/tourist.md
      - getting_started/workflows/tourist_plus.md
      - getting_started/workflows/web.md
      - getting_started/workflows/maivin.md
  - Studio:
    - studio/index.md
    - studio/home.md
    - studio/navigation.md
    - User Management:
      - studio/user/index.md
      - studio/user/profile.md
      - studio/user/organization.md
      - studio/user/billing.md
    - studio/projects.md
    - Datasets Dashboard:
      - studio/datasets/index.md
      - studio/datasets/gallery.md
      - studio/datasets/annotations.md
    - studio/models.md
    - studio/instances.md
    - studio/snapshots.md
    - studio/agtg.md
  - 3D MLOps:
    - 3D/index.md
    - 3D/viewers.md
    - Workflows:
      - 3D/annotation.md
      - 3D/training.md
      - 3D/validation.md
      - 3D/deployment.md
  - Datasets:
    - datasets/index.md
    - EdgeFirst Dataset Format:
      - datasets/format/index.md
      - datasets/format/box_format.md
    - datasets/structure.md
    - Dataset Zoo:
      - Coffee Cup:
        - datasets/coffeecup/index.md
      - Playing Cards:
        - datasets/playingcards/index.md
      - BDD100K:
        - datasets/bdd100k/index.md
      - COCO People:
        - datasets/coco_people/index.md
      - COCO:
        - datasets/coco/index.md
        - datasets/coco/import.md
      - Raivin Ultra Short:
        - datasets/raivin_ultra_short/index.md
    - Dataset Tutorials:
      - datasets/tutorials/index.md
      - datasets/tutorials/capture.md
      - datasets/tutorials/import.md
      - Dataset Annotations:
        - datasets/tutorials/annotations/index.md
        - datasets/tutorials/annotations/automatic.md
        - datasets/tutorials/annotations/manual.md
      - datasets/tutorials/management.md
  - Models:
    - models/index.md
    - Model Training:
      - models/training/vision.md
      - models/training/fusion.md
    - Model Validation:
      - Validating Vision Models:
        - models/validation/vision/managed.md
        - models/validation/vision/user_managed.md
      - Validating Fusion Models:
        - models/validation/fusion/managed.md
      - Model Metrics:
        - models/validation/metrics/detection.md
        - models/validation/metrics/segmentation.md
        - models/validation/metrics/fusion.md
        - models/validation/metrics/matching.md
    - Model Deployment:
      - 2D Model Deployment:
        - models/deployment/pc.md
        - models/deployment/evk.md
        - models/deployment/maivin.md
        - models/deployment/2d_raivin.md
      - 3D Model Deployment:
        - models/deployment/3d_raivin.md
    - Model Zoo:
      - ModelPack:
        - models/modelpack/index.md
        - Quick Start Guide:
          - models/modelpack/tutorials/index.md
          - models/modelpack/tutorials/measurement_tape.md
          - models/modelpack/tutorials/musicbox.md
        - Benchmarks: models/modelpack/benchmarks.md
      - Ultralytics:
          - models/ultralytics/index.md
          - Benchmarks: models/ultralytics/benchmarks.md
      - Fusion:
        - models/fusion/index.md
        - Benchmarks: models/fusion/benchmarks.md
      - Custom Models: 
        - models/custom/index.md
        - models/custom/quantize.md
        - models/custom/npu.md
        - models/custom/neutron.md
    - models/metadata.md
    - models/augmentations.md
  - Perception:
    - perception/index.md
    - Dataset Collection Middleware:
      - platforms/recording.md
      - platforms/replay.md
      - platforms/publishing.md
      - platforms/foxglove.md
      - platforms/advanced_foxglove.md
    - perception/studio.md
    - perception/launcher.md
    - Topics:
      - perception/topics.md
      - perception/topics/camera.md
      - perception/topics/fusion.md
      - perception/topics/imu.md
      - perception/topics/lidar.md
      - perception/topics/model.md
      - perception/topics/navsat.md
      - perception/topics/radar.md
    - Developer Guide:
      - perception/dev.md
      - Examples:
        - perception/dev/examples/camera.md
        - perception/dev/examples/fusion.md
        - perception/dev/examples/gps.md
        - perception/dev/examples/imu.md
        - perception/dev/examples/lidar.md
        - perception/dev/examples/model.md
        - perception/dev/examples/pcd.md
        - perception/dev/examples/radar.md
        - perception/dev/examples/ssd.md
    - API Reference:
      - perception/api.md
      - perception/api/edgefirst_msgs.md
      - perception/api/foxglove_msgs.md
      - perception/api/geometry_msgs.md
      - perception/api/nav_msgs.md
      - perception/api/sensor_msgs.md
      - perception/api/std_msgs.md
      - perception/api/builtin_interfaces.md
      - perception/api/studio.md
    - Deep View RT:
      - perception/deepviewrt/index.md
  - Platforms:
    - platforms/index.md
    - Getting Started:
      - platforms/quickstart.md
      - platforms/walkthrough.md
      - platforms/architecture.md
    - Hardware:
      - platforms/hardware.md
      - platforms/radar.md
      - platforms/lidar.md
    - Software:
      - platforms/configuration.md
      - platforms/model_uploads.md
      - platforms/updates.md
      - platforms/release_notes.md
      - platforms/issues.md
    - Networking:
      - platforms/networking.md
      - platforms/ssh.md