nav:
  - Home: index.md
  - Getting Started:
    - getting_started/index.md
    - getting_started/dataset.md
    - getting_started/models.md
    - getting_started/modules.md
  - enterprise
  - Datasets:
    - datasets/index.md
    - datasets/tutorials.md
    - datasets/zoo.md
    - datasets/format.md
  - models
  - fusion
  - Middleware:
    - middleware/index.md
    - Dataset Collection Middleware:
      - modules/recording.md
      - modules/replay.md
      - modules/publishing.md
      - modules/foxglove.md
      - modules/advanced_foxglove.md
    - middleware/topics.md
    - middleware/custom.md
    - API Reference:
      - middleware/api.md
      - middleware/api/edgefirst_msgs.md
      - middleware/api/foxglove_msgs.md
      - middleware/api/geometry_msgs.md
      - middleware/api/nav_msgs.md
      - middleware/api/sensor_msgs.md
      - middleware/api/std_msgs.md
      - middleware/api/builtin_interfaces.md
  - Modules:
    - modules/index.md
    - Introduction:
      - modules/quickstart.md
      - modules/walkthrough.md
    - Hardware and OS:
      - modules/hardware.md
      - modules/radar.md
      - modules/fusion.md
      - modules/perception.md
      - modules/architecture.md
      - modules/networking.md
      - modules/ssh.md
    - Software:
      - modules/configuration.md
      - modules/troubleshooting.md
      - modules/issues.md
      - modules/release_notes.md
      - modules/updates.md
